language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

install: composer install --dev

script:
  - phpunit --coverage-clover ./build/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/clover.xml

matrix:
  allow_failures:
    - php: hhvm